spring:
  application:
    name: coc-reddit-recruitter

app-config:
  # cron-hello: "0 0 18 * * MON"
  cron-hello: "0 21 0 * * *"
  zone: America/New_York

clashhitters:
  clan-tag: "#8VV2CGYY"
  base-url: https://clashhitters.com
  recruit-stats-uri: /api/recruit-stats-data
